# Generated by Django 3.0.5 on 2020-05-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=254)),
                ('last_name', models.CharField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=254)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address_1', models.CharField(default='', max_length=254)),
                ('address_2', models.CharField(default='', max_length=254)),
                ('address_3', models.CharField(default='', max_length=254)),
                ('address_4', models.CharField(default='', max_length=254)),
                ('postcode', models.CharField(default='', max_length=254)),
            ],
        ),
    ]
