# Generated by Django 3.0.5 on 2020-06-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_title',
            field=models.CharField(max_length=1000),
        ),
    ]
