# Generated by Django 3.0.5 on 2020-05-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Order Received', 'Order Received'), ('Order Sent', 'Order Sent'), ('Order Delivered', 'Order Delivered')], max_length=254, null=True)),
            ],
        ),
    ]
