# Generated by Django 3.0.5 on 2020-05-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_note_1',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='base_note_2',
            field=models.CharField(default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='heart_note_1',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='heart_note_2',
            field=models.CharField(default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top_note_1',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='top_note_2',
            field=models.CharField(default='', max_length=254, null=True),
        ),
    ]
