# Generated by Django 3.0.5 on 2020-05-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200507_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='top_note_2',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
