# Generated by Django 3.0.5 on 2020-05-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200522_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_id',
            field=models.CharField(default='', max_length=254),
        ),
    ]
