# Generated by Django 3.0.7 on 2020-06-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='top_note_2',
        ),
    ]
